### ISSUE TITLE
Move to LSP organization

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-yaml#2]
Would you be open to moving this package to Submlime LSP organization (https://github.com/sublimelsp/)? You would get permissions to maintain it there.

**Comment by RandomByte** [comment]
Sure! That would be great.

Should I transfer it via GitHub or would you rather create a new repository in sublimelsp? I'm open to both

**Comment by rchl** [comment]
I think transferring should work. @rwols?

**Comment by RandomByte** [comment]
In that case I would need permission "to create a repository in the target organization."

From https://help.github.com/en/github/administering-a-repository/transferring-a-repository:
> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

**Comment by rchl** [comment]
I've invited you and also created empty repo at https://github.com/sublimelsp/LSP-yaml

We will need to adjust your permissions after you accept the invitation.

Let me not if that works for you.

**Comment by RandomByte** [comment]
Thanks! I accepted the invite. However, as per above documentation:

> The target account must not have a repository with the same name, or a fork in the same network.

Otherwise I won’t be able to transfer this repository to the org.

**Comment by rchl** [comment]
@RandomByte sorry might have messed up the first time. Lets try again.

**Comment by RandomByte** [comment]
Accepted again :)

Still, https://github.com/sublimelsp/LSP-yaml needs to be deleted before I can transfer. Currently I get the error "sublimelsp/LSP-yaml already exists"

**Comment by rchl** [comment]
@RandomByte hmm, would it be possible for you to make me admin of your repo so that I can transfer it. It's because I don't see a way to give you just the needed permission without making you an admin of whole organization.

**Comment by RandomByte** [comment]
The blocking repository got deleted, so I was able to initiate the transfer. It looks like it worked 👍

**Comment by rchl** [comment]
Looks good to me. :)

**Comment by RandomByte** [comment]
Perfect! I also updated my PR for Package Control: https://github.com/wbond/package_control_channel/pull/7906

**Comment by FichteFoll** [comment]
> It's because I don't see a way to give you just the needed permission without making you an admin of whole organization.

For the record, and since I had to deal with a similar situation a few weeks ago, you just need to configure that every member of the organization can create repositories, which is the default basically required by GitHub. Here are the settings for @SublimeText:

![2020-04-27_19-49-09](https://user-images.githubusercontent.com/931051/80403660-3d31e580-88c0-11ea-9b0a-f666504eff79.png)

You don't receive any other permissions outside of the repositories you create.
