### ISSUE TITLE
Allow specifying initializationOptions

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-yaml#3]
I think it would make sense to also read `initializationOptions` from settings here:
https://github.com/RandomByte/LSP-yaml/blob/88fe49bd0eb96d6866e44afe25d4ca68e5f65fb7/plugin.py#L67
I don't know if server utilizes it for anything but regardless it would be good to allow that as it's something that is defined by spec.

**Comment by RandomByte** [comment]
It's not in their [documentation](https://github.com/redhat-developer/yaml-language-server) but I already saw some undocumented features in their code. So sure, why not :+1:

**Comment by jfcherng** [comment]
I think this is now auto done in the NpmClientHandler?

**Comment by rchl** [comment]
Yes.
