### ISSUE TITLE
How to add another schema definition references?

### ISSUE THREAD

**Issue by gregorip02** [sublimelsp/LSP-yaml#41]
Currently serverless.yml is not supported, how can i add this definition? 
https://raw.githubusercontent.com/softprops/serverless-yml-schema/master/serverless-schema.json

**Comment by rchl** [comment]
You can add an annotation to your yaml file, specifying the schema it should use: https://github.com/redhat-developer/yaml-language-server#using-inlined-schema

If that's not an option for some reason then you can also create association through the LSP-yaml settings (https://github.com/redhat-developer/yaml-language-server#using-yamlschemas-settings) but there is currently a bug that makes it not work (https://github.com/sublimelsp/LSP/issues/1858).

**Comment by gregorip02** [comment]
Great, inline schema worked for me, thanks!!
