### ISSUE TITLE
[support schema] There is no schema that supports yaml

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP-yaml#58]
[Spring schema](https://www.springframework.org/schema/)

**Comment by jingyuexing** [comment]
- [  ] [Websocket](https://www.springframework.org/schema/websocket/spring-websocket.xsd)
- [  ] [aop](https://www.springframework.org/schema/aop/spring-aop.xsd)
- [  ] [batch-integration](https://www.springframework.org/schema/batch-integration/spring-batch-integration.xsd)
- [  ] [spring-batch](https://www.springframework.org/schema/batch/spring-batch.xsd)
- [  ] [spring-beans](https://www.springframework.org/schema/beans/spring-beans.xsd)
- [  ] [spring-boot-layers](https://www.springframework.org/schema/boot/layers/layers.xsd)
- [  ] [etc](#)

**Comment by rchl** [comment]
I have no idea about this.
This server supports schemas from https://www.schemastore.org/json/ and also other arbitrary schema definitions using inline comments (see https://github.com/redhat-developer/yaml-language-server#using-inlined-schema).

I think schemas have to be in yaml format though.

You can ask for more details at the source in https://github.com/redhat-developer/yaml-language-server
