### ISSUE TITLE
Custom Tags have no effect

### ISSUE THREAD

**Issue by daniele-niero** [sublimelsp/LSP-yaml#61]
Hello,

I have followed the example [here](https://github.com/redhat-developer/yaml-language-server#language-server-settings) for setting custom tags, however I still see signed them as an error in a Yaml file.

I'm working on Windows 10, Sublime Stable Channel, Build 4143

**Comment by daniele-niero** [comment]
I've founded.
There was a couple of issues:

1. "yaml.customTags" is inside another object called "settings". That was a bit odd, since these are already settings. So settings inside settings :/
    Anyway, after adding that !Scalar-example and !Seq-example started to work, **but not !Mapping-example**
2. The problem is that documentation says: 
    > The type of object can be either scalar (for strings and booleans), sequence (for arrays), **map** (for objects).  

    But it is not **map** it is **mapping**. So the documentation should be changed.

After adjusting this two details, it worked as expected.

**Comment by jfcherng** [comment]
Closed as resolved.
