### ISSUE TITLE
Element description in hover element is improperly formatted

### ISSUE THREAD

**Issue by PatTheMav** [sublimelsp/LSP-yaml#62]
When hovering the mouse over a token for which a schema provides a description (e.g. a GitHub Actions workflow file), the text in the hover is malformatted:

<img width="928" alt="LSP-yaml Hover Windows with malformatted text" src="https://user-images.githubusercontent.com/9436503/235189644-d25f75ed-ef0c-4fb3-89cd-439c6f239003.png">

The link pointing to the definition doesn't work either.

**Comment by jfcherng** [comment]
Could you provide a reproducer for this, say, a "GitHub Actions workflow file".

**Comment by PatTheMav** [comment]
Here's a sample file - it needs to be placed in a directory tree of `.github/workflows` to trigger the automatic schema detection (root directory does not need to be a git repository).

[test.yml.zip](https://github.com/sublimelsp/LSP-yaml/files/11356281/test.yml.zip)

Hovering the mouse over any keyword (e.g. `permissions`, `on`, or `jobs`) has this issue for me.

**Comment by rchl** [comment]
It's a server issue. They have fixed it but have not release new stable version yet. I will update to latest pre-release version in https://github.com/sublimelsp/LSP-yaml/pull/63 to resolve it though.

**Comment by PatTheMav** [comment]
Thanks for the quick turnaround. 👍🏻
