### ISSUE TITLE
Incompatible with Sublime 4?

### ISSUE THREAD

**Issue by m4sterbunny** [sublimelsp/LSP-yaml#68]
In Sublime 4180, adding LSP server + yaml doesn't result in linting for yaml, works for JSON
![image](https://github.com/user-attachments/assets/e4524e22-95d8-42f2-ae5c-0f3673c5b8ff)
Line 3 should be highlighted as error
![image](https://github.com/user-attachments/assets/8834cb04-ce6b-48d5-bf1d-a3e23a4070b0)

**Comment by jfcherng** [comment]
I would recommend a restart after installation. Not sure whether it's required though. Otherwise, please run ![image](https://github.com/user-attachments/assets/c499bb2d-6dd9-48a2-a45f-b29e00435b49) for it and post the result.

**Comment by m4sterbunny** [comment]
How you managing that?! https://lsp.sublimetext.io/troubleshooting/ says `Run LSP: Toggle Log Panel` and I don't seem to be able to do that. 
But, the 2nd step shows: Unable to open /Users/{userid}/Library/Application Support/Sublime Text/Packages/LSP-yaml/LSP-yaml.sublime-settings
Unable to open /Users/{userid}/Library/Application Support/Sublime Text/Packages/User/LSP-yaml.sublime-settings

**Comment by jfcherng** [comment]
That looks like you didn't install `LSP`.

**Comment by m4sterbunny** [comment]
Ah -- I suspect I broke stuff trying to fix stuff. Typical PEBKAC. Thanks!
