### ISSUE TITLE
Update redhat-developer/yaml-language-server 0.9.0

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP-yaml#9]
Changelog: https://github.com/redhat-developer/yaml-language-server/blob/0.9.0/CHANGELOG.md#090

**Comment by jfcherng** [comment]
:thinking:

**Comment by RandomByte** [comment]
It took me a while to find time to to update this project and properly test it. Please always feel free to propose a PR or give feedback if you tested any of the existing PRs.

I don't want to claim ownership over this repository (it's open source and part of the "SublimeLSP" org after all), just some responsibility.

May I ask, what's the difference to your [LSP-yaml](https://github.com/jfcherng-sublime/LSP-yaml) project now? Should we include some of those changes in this project? Do you want to become a contributor here?

**Comment by jfcherng** [comment]
> May I ask, what's the difference to your [LSP-yaml](https://github.com/jfcherng-sublime/LSP-yaml) project now? Should we include some of those changes in this project? Do you want to become a contributor here?

It looks like they are the same now (except for folder naming and mine only works on ST 4). :+1:

**Comment by jfcherng** [comment]
You can use the dependabot https://github.com/jfcherng-sublime/LSP-yaml/tree/master/.dependabot to auto create an issue on GitHub if there is a new release for the server.

**Comment by jfcherng** [comment]
I am going to switch back to `sublimelsp/LSP-yaml` and delete my repo soon since my repo doesn't provide anything extra.

**Comment by RandomByte** [comment]
Awesome, thanks!

Should I just add you as a contributor so you can manage this repository as well? I think that just makes sense, given your experience. If you are happy with a change you can then make the releases yourself. Or request a review if you want any feedback.

> I would like to promote using language-server as the server directory name for consistency but, well, not really important.

Sounds good :+1:
